<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>be493df9-6db0-402d-bd04-59ed63fa0b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Sony DualSense Wireless Controller Ice Blue (PlayStation 5)&quot;] > div.b5zgse-0.sc-1tzwjyb-0.gReMEq.jUZAZr > div.sc-1myhuh-0.jAcwUT > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gcx-gf-section-1']/div/section/div[5]/figure/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7f72220-5e47-4c9b-bb5a-d08c1b3dbed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/31f452csReL._AC_SY164_.jpg</value>
      <webElementGuid>a36e91f3-de31-405a-bedd-6a1d05692966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/31f452csReL._AC_SY328_.jpg</value>
      <webElementGuid>65070a94-642c-4e30-bfaa-1372aa96d94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gcx-gf-section-1&quot;)/div[@class=&quot;sc-15wd500-0 hjMJzD&quot;]/section[@class=&quot;sc-1koy58b-0 jChBdP&quot;]/div[@class=&quot;d4xojt-0 cNEYvG&quot;]/figure[@class=&quot;sc-19uhyhx-1 bHjryZ&quot;]/div[@class=&quot;b5zgse-0 sc-1tzwjyb-0 kxVzkh jWvTKO&quot;]/a[1]/div[@class=&quot;b5zgse-0 sc-1tzwjyb-0 gReMEq jUZAZr&quot;]/div[@class=&quot;sc-1myhuh-0 jAcwUT&quot;]/img[1]</value>
      <webElementGuid>dafbd8a3-2d19-4c1f-9987-3f06ba83aeb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gcx-gf-section-1']/div/section/div[5]/figure/div/a/div/div/img</value>
      <webElementGuid>fca25010-e46b-4cdd-9479-f821003199ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://m.media-amazon.com/images/I/31f452csReL._AC_SY164_.jpg')]</value>
      <webElementGuid>0c088f1f-5201-47aa-ad66-48eefc20fb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/section/div[5]/figure/div/a/div/div/img</value>
      <webElementGuid>7724e2cb-61aa-4109-9330-8347b137d1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/31f452csReL._AC_SY164_.jpg']</value>
      <webElementGuid>560a6757-1f5b-4810-89d6-a8c4c9d5659d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
