<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gift Ideas</name>
   <tag></tag>
   <elementGuidId>03a4d910-698d-4d1c-8665-e236cadb6df1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5080318a-1b3c-4ea0-946a-04b43f4fae25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gcx/-/gfhz/?ref_=nav_cs_giftfinder</value>
      <webElementGuid>9430b214-baf2-48a8-b9c9-227fa1a6b13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>a2d7b246-1ae9-473a-b043-7a38909ff665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>990e5443-04f0-4002-a3e9-7ff6b7dcb7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>16a36e01-618d-41db-b0bf-c4cae11a51d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_7</value>
      <webElementGuid>28998930-ab44-49f2-a710-928213b72447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_giftfinder</value>
      <webElementGuid>09a89070-3d88-4bdc-9e41-0de001689702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>jvr15p-c3jk23-wvlln1-5iyufw</value>
      <webElementGuid>0d28cce6-b83c-4161-b542-9d95b3ce7928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gift Ideas	</value>
      <webElementGuid>06020e4d-b9b2-4584-8ba8-6a56afa99e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>05a2502b-6ede-403b-b246-6b3bd07eb13e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[8]</value>
      <webElementGuid>355756fb-9835-4462-967f-5dbb2ffd7f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gift Ideas')]</value>
      <webElementGuid>2bb9b235-d7fd-400d-b1f1-6829b5e7a507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gcx/-/gfhz/?ref_=nav_cs_giftfinder')]</value>
      <webElementGuid>8d61296c-e450-4b5d-bad7-f7ddebd29525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[8]</value>
      <webElementGuid>a1f3534b-1bdb-410b-b882-c54e09407690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gcx/-/gfhz/?ref_=nav_cs_giftfinder' and (text() = 'Gift Ideas	' or . = 'Gift Ideas	')]</value>
      <webElementGuid>b8265098-03d3-436f-b73f-b2c969e22d10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
