<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AL FASCINO Wallets for men leather ori_ec0ab0</name>
   <tag></tag>
   <elementGuidId>63a7fe3d-3376-4992-b5f4-2984ea4808ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;AL FASCINO Wallets for men leather original purses for men rfid wallet for men leather wallet for men money purse for men Wallet Mens wallet men wallet gents wallets wallet for men card holder for men gents wallets&quot;] > div.b5zgse-0.sc-1tzwjyb-0.czmBfq.cFehYK > div.b5zgse-0.kxVzkh > div.b5zgse-0.kxVzkh > div.b5zgse-0.bXthBS > span.sc-167fkr-0.z5x770-0.hoLOMk.iJcgAl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gcx-gf-section-0']/div/section/div[6]/figure/div/a/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4f348cb8-f1a8-46a7-b85b-a4d3b9a46acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overflow</name>
      <type>Main</type>
      <value>allow</value>
      <webElementGuid>19af1c56-37db-4807-969b-3f1b95be7b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>692abe6a-14e1-49c9-a474-4857fbcbc568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-style</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>0900cd56-1a55-49d9-93d6-96215d546456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-167fkr-0 z5x770-0 hoLOMk iJcgAl</value>
      <webElementGuid>d1583910-a206-4e46-a70d-1e18a474c396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AL FASCINO Wallets for men leather original purses for men rfid wallet for men leather wallet for men money purse for men Wallet Mens wallet men wallet gents wallets wallet for men card holder for men gents wallets</value>
      <webElementGuid>1b19ac5b-f0ed-405b-ada5-8a923f5ad1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gcx-gf-section-0&quot;)/div[@class=&quot;sc-15wd500-0 hjMJzD&quot;]/section[@class=&quot;sc-1koy58b-0 jChBdP&quot;]/div[@class=&quot;d4xojt-0 eXUDxP&quot;]/figure[@class=&quot;sc-19uhyhx-1 bHjryZ&quot;]/div[@class=&quot;b5zgse-0 sc-1tzwjyb-0 kxVzkh jWvTKO&quot;]/a[1]/div[@class=&quot;b5zgse-0 sc-1tzwjyb-0 czmBfq cFehYK&quot;]/div[@class=&quot;b5zgse-0 kxVzkh&quot;]/div[@class=&quot;b5zgse-0 kxVzkh&quot;]/div[@class=&quot;b5zgse-0 bXthBS&quot;]/span[@class=&quot;sc-167fkr-0 z5x770-0 hoLOMk iJcgAl&quot;]</value>
      <webElementGuid>2766d76c-75f0-4f93-a247-ce6df7ced0a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gcx-gf-section-0']/div/section/div[6]/figure/div/a/div[2]/div/div/div/span</value>
      <webElementGuid>c5cf4af0-e268-45d8-b6f3-cdbc1d4a8880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/figure/div/a/div[2]/div/div/div/span</value>
      <webElementGuid>4265a8f9-d8c8-4ee5-bef0-9c4fc330b519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AL FASCINO Wallets for men leather original purses for men rfid wallet for men leather wallet for men money purse for men Wallet Mens wallet men wallet gents wallets wallet for men card holder for men gents wallets' or . = 'AL FASCINO Wallets for men leather original purses for men rfid wallet for men leather wallet for men money purse for men Wallet Mens wallet men wallet gents wallets wallet for men card holder for men gents wallets')]</value>
      <webElementGuid>6f87ce20-8eaf-4dc4-bca1-37947a1d823f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
